---
- hosts: aristaswitches
  connection: network_cli
  gather_facts: yes
  vars:
    vlans: "{{ hostvars['local']['vlanlist'] }}"
  tasks:
    - name: verzamel informatie van de arista switch
      eos_facts:

    - name: Versie Switch
      debug:
        msg: "The EOS version is: {{ ansible_net_version }}"

    - name: Hostname Switch
      debug:
        msg: "The hostname is: {{ ansible_net_hostname }}"
        
    - name: Toevoegen vlans allow aan ethernent 2 trunk
      eos_l2_interface:
        name: Ethernet2
        mode: trunk
        native_vlan: 2
        trunk_allowed_vlans: ["10","20","30"]
      loop: "{{ vlans }}"
      when: item != 0      
      tags: show

    - name: Waardes van opgegeven show commando's
      eos_command:
        commands:
          - show run | i hostname
          - show ip interface brief
          - show interfaces ethernet 2 trunk #laat de actieve trunks zien
      register: show_output

    - name: Laat de show waardes in debugging zien
      debug:
        var: show_output
      tags: show

    - name: Laat de hostname van de switch in debugging zien
      debug:
        msg: "The hostname is {{ show_output.stdout[0] }}"
      tags: show