- hosts: arubaswitches
  roles: 
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Adding or Updating Banner
      aoscx_banner:
        banner_type: banner
        banner: "--------------------------------------------------------------/n     Deze Banner is geplaatst door Ansible                 -"
