- hosts: arubaswitches
  roles: 
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Adding or Updating Banner
      aoscx_banner:
        banner_type: banner
        banner: |
        *************************************************************
        *     Deze Banner is geplaatst door Ansible                 *
        *                                                           *
        *     Access to this computer system is restricted to       *
        *     official use by users authorized by Corp Inc.,        *
        *     and must comply with the Information Security         *
        *     policies listed on the Corp Corporate Intranet at:    *
        *     http://iweb/informationsecurity/documents/            *
        *     policies/Policy.htm                                   *
        *                                                           *
        *     Corp may monitor and disclose information on or       *
        *     about this system, and you should have no             *
        *     expectation of privacy in using it.                   *
        *                                                           *
        *     Your continued use of the system constitutes          *
        *     agreement to these terms. If you do not agree,        *
        *     please disconnect immediately.                        *
        *************************************************************