---
- name: Maak ticket change ticket vanuit Ansible
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: voeg vars bestand toe
    include_vars: var.yml

  - name: Maak een change ticket aan
    snow_record:
      state: present
      table: incident
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_serv_medium }}"
        priority: "{{ sn_prio_medium }}"
        short_description: "This is a test opened by Ansible"
    register: new_incident

  - debug: 
      var: new_incident.record