---
- name: Maak ticket change ticket vanuit Ansible
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: voeg vars bestand toe
    include_vars: change_request_vars.yml

  - name: Maak een change ticket aan
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "This is a test opened by Ansible"
    register: new_incident

  - debug: 
      var: new_incident.record