---
- name: VMware HTTP REST-API Koppeling
  hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - var.yml
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:
  #  - name: Login in vCenter en get cookies
  #    uri:
  #      url: https://{{ servers.vcenter }}/rest/com/vmware/cis/session
  #      force_basic_auth: yes
  #      validate_certs: no
  #      method: POST
  #      user: "{{ username.vcenter }}"
  #      password: "{{ password.vcenter }}"
  #    register: login
  #  - debug: msg="{{ login }}"
      
    #- name: Haal ESXi hosts vanuit vCenter met behulp van cookies van de vorige task
    #  uri:
    #    url: https://{{ servers.vcenter }}/rest/vcenter/host
    #    force_basic_auth: yes
    #    validate_certs: no
    #    headers:
    #      Cookie: "{{ login.set_cookie }}"
    #  register: vchosts

    #- name: Get all VLAN on vswitch
    #  shell: pwsh -File getvlanvswitch.ps1 -usernamevcenter "{{ username.vcenter }}" -passwordvcenter "{{ password.vcenter }}"
    #  ignore_errors: yes
    #  changed_when: false
    #  register: powershell_output
    #- debug: msg="{{ powershell_output.stdout_lines }}"

    - name: Get all VLAN on vdswitch
      vmware_dvs_portgroup_info:
        hostname: "{{ servers.vcenter }}"
        username: "{{ username.vcenter }}"
        password: "{{ password.vcenter }}"
        datacenter: "Campus"
        validate_certs: no
        show_vlan_info: yes
      register: dvpg_info
      
    - debug: msg="{{ dvpg_info }}"
    - name: filter voor vlans
      set_fact:
        vlanlist: "{{vlanlist|default([])}}"
        cacheable: yes
      with_items: "{{ dvpg_info | json_query('msg.dvs_portgroup_info.DSwitch[*].vlan_info.vlan_id') }}"
    - name: vlan list
      debug: var=vlanlist
      