- hosts: 6300-1
  collections:
      - arubanetworks.aoscx
  tasks:
    - name: Create VLAN 300
      arubaoss_vlan:
        vlan_id: 300
        name: "vlan300"
        config: "create"
        command: config_vlan