---
- hosts: arubaswitches
  gather_facts: yes
  vars:
    vlans: "{{ hostvars['local']['vlanlist'] }}"
    vlanvar: "{{ hostvars['local']['vlanlistvar'] }}"
    vlansnozero: "{{ vlanvar | reject('search','0') | list }}"
  roles: 
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Add VLAN "{{ item }}"
      aoscx_vlan:
        vlan_id: "{{ item }}"
        name: "vlan{{ item }}"
        state: "create"
        description: "Automated created vlan {{ item }} met Ansible"
      loop: "{{ vlans }}"
      when: item != 0

- hosts: arubaswitches
  gather_facts: yes
  vars:
    ansible_connection: network_cli
    vlans: "{{ hostvars['local']['vlanlist'] }}"
    vlanvar: "{{ hostvars['local']['vlanlistvar'] }}"
    vlansnozero: "{{ vlanvar | reject('search','0') | list }}"
  roles: 
    - role: arubanetworks.aoscx_role 
  tasks:         
    - name: Add VLAN trunk allowed vlan "{{ item }}"
      aoscx_command:
        commands: ['config',
          'interface 1/1/1',
            'vlan trunk allowed {{ item }}',
          'end']
      loop: "{{ vlans }}"
      when: item != 0

    