---
- hosts: all
  roles: 
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Create VLAN 400
      aoscx_vlan:
        vlan_id: 400
        name: "vlan400"
        state: "create"
        description: "Automated met Ansible"
    - debug: msg="{{ vlanlist }}" 