- hosts: 6300-1
  collections:
      - arubanetworks.aoscx
  tasks:
    - name: Create VLAN 400
      arubaoss_vlan:
        vlan_id: 400
        name: "vlan400"
        config: "create"
        command: config_vlan