---
- hosts: arubaswitches
  gather_facts: yes
  roles: 
    - role: arubanetworks.aoscx_role
  tasks:
    - debug: var=hostvars['local']['vlanlist']    
    - name: Create VLAN 400
      aoscx_vlan:
        vlan_id: "{{ var | int }}"
        name: "vlan400"
        state: "create"
        description: "Automated met Ansible"
    