---
- hosts: arubaswitches
  gather_facts: yes
  vars:
    vlans: "{{ hostvars['local']['vlanlist'] }}"
  roles: 
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Create VLAN 400
      aoscx_vlan:
        vlan_id: "{{ item }}"
        name: "vlan400"
        state: "create"
        description: "Automated met Ansible"
      loop: "{{ vlans }}"
    - debug: msg="{{ vlans }}"
    